In [1]:
import pandas as pd
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split

In [2]:
us_gas_data = pd.read_csv('Resources/Datasets/cleaned_data/us_gas_data.csv')
us_gas_data

,Year,Month,Gas_Production(Mmcf),Gas_Consumption(Mmcf),Import_price($/Mcf),Export_price($/Mcf),Total Imports (Mmcf),Total Exports (Mmcf),all_grades($/Gallon),regular($/Gallon),midgrade($/Gallon),premium($/Gallon),diesel($/Gallon),Volumn(Mmcf)
0,2022,2,2856356,3040029.0,5.62,8.22,259389,545563,3.611,3.517,3.939,4.210,4.032,5997164.0
1,2022,1,3180818,3591557.0,6.87,7.04,296179,610102,3.413,3.315,3.766,4.036,3.724,6653327.0
2,2021,12,3266272,2979653.0,4.74,7.40,252626,620886,3.406,3.307,3.771,4.034,3.641,7647859.0
3,2021,11,3161306,2659971.0,5.18,8.10,242405,556982,3.491,3.395,3.836,4.098,3.727,7971480.0
4,2021,10,3219612,2237715.0,4.79,7.97,228203,545055,3.384,3.291,3.723,3.979,3.612,8103211.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,2001,5,1763141,1522382.0,4.95,5.50,321878,28981,1.738,1.702,1.785,1.869,1.496,5749464.0
250,2001,4,1703310,1807170.0,5.35,5.65,318573,23637,1.591,1.552,1.646,1.732,1.422,5252851.0
251,2001,3,1766754,2246633.0,5.42,4.93,358103,32121,1.450,1.409,1.506,1.596,1.399,5041971.0
252,2001,2,1582557,2309464.0,6.45,5.80,328289,26882,1.490,1.450,1.544,1.635,1.492,5240820.0
253,2001,1,1753237,2676998.0,9.47,7.48,373077,25547,1.487,1.447,1.541,1.630,1.524,5609446.0

In [3]:
us_gas_data.columns

Index(['Year', 'Month', 'Gas_Production(Mmcf)', 'Gas_Consumption(Mmcf)',
       'Import_price($/Mcf)', 'Export_price($/Mcf)', 'Total Imports (Mmcf)',
       'Total Exports (Mmcf)', 'all_grades($/Gallon)', 'regular($/Gallon)',
       'midgrade($/Gallon)', 'premium($/Gallon)', 'diesel($/Gallon)',
       'Volumn(Mmcf)'],
      dtype='object')

In [4]:
us_gas_data.dtypes

Year                       int64
Month                      int64
Gas_Production(Mmcf)       int64
Gas_Consumption(Mmcf)    float64
Import_price($/Mcf)      float64
Export_price($/Mcf)      float64
Total Imports (Mmcf)       int64
Total Exports (Mmcf)       int64
all_grades($/Gallon)     float64
regular($/Gallon)        float64
midgrade($/Gallon)       float64
premium($/Gallon)        float64
diesel($/Gallon)         float64
Volumn(Mmcf)             float64
dtype: object

In [6]:
us_gas_data = us_gas_data.astype({'Gas_Production(Mmcf)':float,
                                  'Total Imports (Mmcf)' : float,
                                  'Total Exports (Mmcf)': float})
us_gas_data.dtypes

Year                       int64
Month                      int64
Gas_Production(Mmcf)     float64
Gas_Consumption(Mmcf)    float64
Import_price($/Mcf)      float64
Export_price($/Mcf)      float64
Total Imports (Mmcf)     float64
Total Exports (Mmcf)     float64
all_grades($/Gallon)     float64
regular($/Gallon)        float64
midgrade($/Gallon)       float64
premium($/Gallon)        float64
diesel($/Gallon)         float64
Volumn(Mmcf)             float64
dtype: object

In [7]:
us_gas_data.describe()

,Year,Month,Gas_Production(Mmcf),Gas_Consumption(Mmcf),Import_price($/Mcf),Export_price($/Mcf),Total Imports (Mmcf),Total Exports (Mmcf),all_grades($/Gallon),regular($/Gallon),midgrade($/Gallon),premium($/Gallon),diesel($/Gallon),Volumn(Mmcf)
count,254.000000,254.000000,2.540000e+02,2.540000e+02,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,2.540000e+02
mean,2011.086614,6.460630,2.130387e+06,2.127122e+06,4.459764,4.955591,288559.976378,168158.531496,2.629945,2.562823,2.753433,2.909291,2.798303,6.906497e+06
std,6.121334,3.473847,5.071507e+05,4.740569e+05,2.161772,1.964109,58264.662838,146897.706073,0.718712,0.713631,0.736901,0.761305,0.844100,8.031707e+05
min,2001.000000,1.000000,1.400941e+06,1.368369e+06,1.510000,2.040000,174225.000000,23637.000000,1.127000,1.086000,1.179000,1.271000,1.152000,5.041971e+06
25%,2006.000000,3.000000,1.694616e+06,1.743070e+06,2.732500,3.510000,238368.750000,64439.500000,2.198500,2.109250,2.287750,2.430750,2.311250,6.288639e+06
50%,2011.000000,6.000000,1.994746e+06,2.068744e+06,4.035000,4.450000,282064.500000,118918.500000,2.640500,2.555000,2.786000,2.950500,2.839500,7.002317e+06
75%,2016.000000,9.000000,2.428004e+06,2.428177e+06,5.627500,6.015000,333876.250000,224495.750000,3.124000,3.062000,3.247750,3.470250,3.374000,7.545798e+06
max,2022.000000,12.000000,3.266272e+06,3.591557e+06,11.990000,12.680000,426534.000000,620886.000000,4.114000,4.062000,4.181000,4.298000,4.703000,8.384087e+06

In [9]:
#group by data 'year'- all gas data
annual_gas_production = us_gas_data.groupby(['Year']).mean()['Gas_Production(Mmcf)']
annual_gas_consumption = us_gas_data.groupby(['Year']).mean()['Gas_Consumption(Mmcf)']
annual_gas_import_p = us_gas_data.groupby(['Year']).mean()['Import_price($/Mcf)']
annual_gas_export_p = us_gas_data.groupby(['Year']).mean()['Export_price($/Mcf)']
annual_total_import = us_gas_data.groupby(['Year']).mean()['Total Imports (Mmcf)']
annual_total_export = us_gas_data.groupby(['Year']).mean()['Total Exports (Mmcf)']
annual_avg_all_grades_p = us_gas_data.groupby(['Year']).mean()['all_grades($/Gallon)']
annual_avg_reg_p = us_gas_data.groupby(['Year']).mean()['regular($/Gallon)']
annual_avg_midg_p = us_gas_data.groupby(['Year']).mean()['midgrade($/Gallon)']
annual_avg_pre_p = us_gas_data.groupby(['Year']).mean()['premium($/Gallon)']
annual_avg_dis_p = us_gas_data.groupby(['Year']).mean()['diesel($/Gallon)']
annual_avg_vol = us_gas_data.groupby(['Year']).mean()['Volumn(Mmcf)']

In [10]:
# create annual summary, reorder columns
annual_gas_summary = pd.DataFrame({
    'avg_production(Mmcf)': annual_gas_production,
    'avg_consumption(Mmcf)': annual_gas_consumption,
    'avg_vol(Mmcf)': annual_avg_vol,
    'avg_total_import(Mmcf)': annual_total_import,
    'avg_toal_export(Mmcf)': annual_total_export,
    'avg_import_price($/Mmcf)': annual_gas_import_p,
    'avg_export_price($/Mmcf)': annual_gas_export_p,
    'avg_all_grades_p($/Gallon)': annual_avg_all_grades_p,
    'avg_reg_p($/Gallon)': annual_avg_reg_p,
    'avg_midg_p($/Gallon)': annual_avg_midg_p,
    'avg_pre_p($/Gallon)': annual_avg_pre_p,
    'avg_dis_p($/Gallon)': annual_avg_dis_p 
})

annual_gas_summary.head()

,avg_production(Mmcf),avg_consumption(Mmcf),avg_vol(Mmcf),avg_total_import(Mmcf),avg_toal_export(Mmcf),avg_import_price($/Mmcf),avg_export_price($/Mmcf),avg_all_grades_p($/Gallon),avg_reg_p($/Gallon),avg_midg_p($/Gallon),avg_pre_p($/Gallon),avg_dis_p($/Gallon)
Year,,,,,,,,,,,,
2001,1.714191e+06,1.853219e+06,6.335558e+06,331411.500000,31106.583333,4.357500,4.383333,1.466167,1.426000,1.518833,1.607917,1.404083
2002,1.657065e+06,1.918918e+06,6.715545e+06,334622.000000,43019.333333,3.138333,3.339167,1.381833,1.340333,1.435250,1.525833,1.315333
2003,1.664530e+06,1.856375e+06,6.256805e+06,328645.750000,56660.250000,5.180833,5.582500,1.601083,1.559167,1.656333,1.746000,1.508333
2004,1.626458e+06,1.866879e+06,6.460054e+06,354879.916667,71178.083333,5.779167,6.069167,1.891250,1.848750,1.946917,2.038417,1.807500
2005,1.577258e+06,1.834536e+06,6.492884e+06,361752.833333,60716.666667,8.085000,8.010833,2.312167,2.268167,2.367583,2.465917,2.398667

In [11]:
four_more_factors_yrly = pd.read_csv('Resources/Datasets/cleaned_data/4_more_factors.csv')
four_more_factors_yrly

    Year  inflation(%)  stock_to_GDP(%)  working_population  Interest_Rate(%)
0   2001      2.826171         132.1480           181476647          3.410000
1   2002      1.586032         101.0791           183792729          1.173333
2   2003      2.270095         124.5066           186939817          2.104167
3   2004      2.677237         133.6506           188763071          2.395833
4   2005      3.392747         130.4083           191024953          4.250000
5   2006      3.225944         141.6542           193219398          6.020833
6   2007      2.852672         137.8527           195663562          5.791667
7   2008      3.839100          78.7766           196691536          2.166667
8   2009     -0.355546         104.3488           197897475          0.500000
9   2010      1.640043         115.2841           199183839          0.729167
10  2011      3.156842         100.6313           199962562          0.750000
11  2012      2.069337         115.2579           201475828          0.750000
12  2013      1.464833         143.1937           202327635          0.750000
13  2014      1.622223         150.2273           203020518          0.750000
14  2015      0.118627         137.4445           204334050          0.770833
15  2016      1.261583         145.9167           205553963          1.020833
16  2017      2.130110         164.3593           205570247          1.625000
17  2018      2.442583         147.6641           206538862          2.458333
18  2019      1.812210         158.1229           206309620          2.750000
19  2020      1.233584         194.4900           205954426          0.583333

In [12]:
annual_gas_summary_more = annual_gas_summary.merge(four_more_factors_yrly, how='inner', on='Year')
annual_gas_summary_more

,Year,avg_production(Mmcf),avg_consumption(Mmcf),avg_vol(Mmcf),avg_total_import(Mmcf),avg_toal_export(Mmcf),avg_import_price($/Mmcf),avg_export_price($/Mmcf),avg_all_grades_p($/Gallon),avg_reg_p($/Gallon),avg_midg_p($/Gallon),avg_pre_p($/Gallon),avg_dis_p($/Gallon),inflation(%),stock_to_GDP(%),working_population,Interest_Rate(%)
0,2001,1.714191e+06,1.853219e+06,6.335558e+06,331411.500000,31106.583333,4.357500,4.383333,1.466167,1.426000,1.518833,1.607917,1.404083,2.826171,132.1480,181476647,3.410000
1,2002,1.657065e+06,1.918918e+06,6.715545e+06,334622.000000,43019.333333,3.138333,3.339167,1.381833,1.340333,1.435250,1.525833,1.315333,1.586032,101.0791,183792729,1.173333
2,2003,1.664530e+06,1.856375e+06,6.256805e+06,328645.750000,56660.250000,5.180833,5.582500,1.601083,1.559167,1.656333,1.746000,1.508333,2.270095,124.5066,186939817,2.104167
3,2004,1.626458e+06,1.866879e+06,6.460054e+06,354879.916667,71178.083333,5.779167,6.069167,1.891250,1.848750,1.946917,2.038417,1.807500,2.677237,133.6506,188763071,2.395833
4,2005,1.577258e+06,1.834536e+06,6.492884e+06,361752.833333,60716.666667,8.085000,8.010833,2.312167,2.268167,2.367583,2.465917,2.398667,3.392747,130.4083,191024953,4.250000
5,2006,1.617473e+06,1.808256e+06,6.860307e+06,348856.833333,60329.750000,6.866667,6.831667,2.615083,2.569167,2.673000,2.775917,2.705000,3.225944,141.6542,193219398,6.020833
6,2007,1.683029e+06,1.925316e+06,6.837505e+06,383965.166667,68537.833333,6.872500,6.905833,2.845500,2.798583,2.905667,3.009500,2.881667,2.852672,137.8527,195663562,5.791667
7,2008,1.759338e+06,1.939751e+06,6.592182e+06,332008.416667,80271.750000,8.774167,8.774167,3.305083,3.251833,3.372917,3.491750,3.806833,3.839100,78.7766,196691536,2.166667
8,2009,1.803995e+06,1.909173e+06,7.052343e+06,312613.333333,89363.083333,4.136667,4.354167,2.396667,2.343500,2.464500,2.581250,2.463667,-0.355546,104.3488,197897475,0.500000
9,2010,1.865156e+06,2.007233e+06,7.052461e+06,311730.000000,94732.416667,4.464167,5.030000,2.833583,2.780333,2.900917,3.020083,2.989333,1.640043,115.2841,199183839,0.729167
10,2011,2.003029e+06,2.039785e+06,7.004209e+06,289057.750000,125470.833333,4.221667,4.640833,3.576417,3.520917,3.644167,3.771000,3.845333,3.156842,100.6313,199962562,0.750000
11,2012,2.106940e+06,2.128207e+06,7.501633e+06,261482.416667,134902.333333,2.880833,3.223333,3.686167,3.625000,3.762000,3.900250,3.970417,2.069337,115.2579,201475828,0.750000
12,2013,2.130186e+06,2.179589e+06,7.149331e+06,240279.666667,131034.416667,3.815000,4.081667,3.576417,3.505917,3.663167,3.822917,3.922917,1.464833,143.1937,202327635,0.750000
13,2014,2.291480e+06,2.216115e+06,6.620863e+06,224614.916667,126186.833333,5.380833,5.410000,3.442000,3.363167,3.544833,3.715750,3.828667,1.622223,150.2273,203020518,0.750000
14,2015,2.397670e+06,2.270321e+06,7.171337e+06,226507.750000,148626.083333,3.153333,3.080000,2.513000,2.422167,2.638167,2.823333,2.706583,0.118627,137.4445,204334050,0.770833
15,2016,2.366671e+06,2.287018e+06,7.577976e+06,250536.500000,194620.666667,2.337500,2.745833,2.252500,2.145833,2.397000,2.618167,2.306167,1.261583,145.9167,205553963,1.020833
16,2017,2.436486e+06,2.261873e+06,7.304990e+06,252768.916667,262817.000000,2.690000,3.535833,2.530333,2.417000,2.684083,2.918917,2.653667,2.130110,164.3593,205570247,1.625000
17,2018,2.750739e+06,2.511578e+06,6.654810e+06,240737.000000,300653.500000,2.812500,3.855833,2.817333,2.723000,3.059500,3.298250,3.178833,2.442583,147.6641,206538862,2.458333
18,2019,3.037243e+06,2.594337e+06,6.901474e+06,228476.333333,388138.083333,2.588333,3.630833,2.685750,2.598250,2.994250,3.246333,3.055583,1.812210,158.1229,206309620,2.750000
19,2020,3.016870e+06,2.539351e+06,7.456273e+06,212611.666667,440300.666667,2.086667,3.624167,2.259750,2.168833,2.584250,2.835333,2.555250,1.233584,194.4900,205954426,0.583333

In [ ]:
# annual_gas_summary_more.to_csv('Resources/cleaned_data/14_variables.csv', index=False)

In [13]:
annual_gas_summary.dtypes

avg_production(Mmcf)          float64
avg_consumption(Mmcf)         float64
avg_vol(Mmcf)                 float64
avg_total_import(Mmcf)        float64
avg_toal_export(Mmcf)         float64
avg_import_price($/Mmcf)      float64
avg_export_price($/Mmcf)      float64
avg_all_grades_p($/Gallon)    float64
avg_reg_p($/Gallon)           float64
avg_midg_p($/Gallon)          float64
avg_pre_p($/Gallon)           float64
avg_dis_p($/Gallon)           float64
dtype: object

# Multilinear Regression with 4 more factors 
### Inflation, Working population, Stock market to GDP Percentage, and Interest_rate

In [14]:
#initialize X, y
X = annual_gas_summary_more.drop(columns = ['avg_all_grades_p($/Gallon)'])
y = annual_gas_summary_more['avg_all_grades_p($/Gallon)'].values.reshape(-1,1)

In [15]:
#Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [16]:
#Scale data
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()
X_train_s = data_scaler.fit_transform(X_train)
X_test_s = data_scaler.fit_transform(X_test)

In [17]:
#create instance of model
model = LinearRegression()

In [18]:
#train the model
model.fit(X_train_s, y_train)

LinearRegression()

In [22]:
#create prediction to test
y_pred = model.predict(X_test_s)

In [23]:
#results
print('Multi-Linear_Regression Model Result:')
print(y_pred.shape)
print('---------------------------------------')
print('intercept: \n', model.intercept_)
print('Coefficients: \n', model.coef_)

Multi-Linear_Regression Model Result:
(5, 1)
---------------------------------------
intercept:
 [2.63623333]
Coefficients:
 [[ 0.02169941 -0.01666174 -0.01625995 -0.00268678  0.01466605 -0.0228708
   0.05621146 -0.06697506  0.32975795  0.23605075  0.06660794  0.03536866
   0.00961803  0.00816742  0.00710507 -0.0106583 ]]

In [24]:
import sklearn.metrics as skm
print('MAE =', round(skm.mean_absolute_error(y_test, y_pred), 2))
print("MSE =", round(skm.mean_squared_error(y_test, y_pred), 2)) 
print("MAE =", round(skm.median_absolute_error(y_test, y_pred), 2)) 
print("EVS =", round(skm.explained_variance_score(y_test, y_pred), 2)) 
print("R2 score =", round(skm.r2_score(y_test, y_pred), 2))

MAE = 0.15
MSE = 0.02
MAE = 0.14
EVS = 1.0
R2 score = 0.95

In [28]:
import statsmodels.api as sm

In [29]:
#initialize X, y
X = annual_gas_summary_more.drop(columns = ['avg_all_grades_p($/Gallon)'])
y = annual_gas_summary_more['avg_all_grades_p($/Gallon)']

In [30]:
X = sm.add_constant(X)

C:\Users\Phoeb\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

In [31]:
sm_model = sm.OLS(y, X).fit()

In [32]:
predictions = sm_model.predict(X)

In [33]:
print(sm_model.summary())

                                OLS Regression Results
======================================================================================
Dep. Variable:     avg_all_grades_p($/Gallon)   R-squared:                       1.000
Model:                                    OLS   Adj. R-squared:                  1.000
Method:                         Least Squares   F-statistic:                 5.064e+04
Date:                        Wed, 25 May 2022   Prob (F-statistic):           1.27e-07
Time:                                20:00:32   Log-Likelihood:                 104.56
No. Observations:                          20   AIC:                            -175.1
Df Residuals:                               3   BIC:                            -158.2
Df Model:                                  16
Covariance Type:                    nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                        4.2629     17.438      0.244      0.823     -51.233      59.758
Year                        -0.0024      0.009     -0.262      0.810      -0.032       0.027
avg_production(Mmcf)      3.028e-08   4.09e-08      0.740      0.513   -9.99e-08     1.6e-07
avg_consumption(Mmcf)    -6.659e-09   4.65e-08     -0.143      0.895   -1.55e-07    1.41e-07
avg_vol(Mmcf)             5.423e-10   9.04e-09      0.060      0.956   -2.82e-08    2.93e-08
avg_total_import(Mmcf)    8.334e-08   1.85e-07      0.450      0.683   -5.06e-07    6.72e-07
avg_toal_export(Mmcf)     6.312e-08   1.52e-07      0.415      0.706   -4.21e-07    5.47e-07
avg_import_price($/Mmcf)     0.0063      0.012      0.509      0.646      -0.033       0.046
avg_export_price($/Mmcf)    -0.0076      0.018     -0.425      0.699      -0.065       0.049
avg_reg_p($/Gallon)          1.3519      0.267      5.067      0.015       0.503       2.201
avg_midg_p($/Gallon)        -1.0818      0.377     -2.871      0.064      -2.281       0.117
avg_pre_p($/Gallon)          0.6677      0.183      3.650      0.036       0.085       1.250
avg_dis_p($/Gallon)          0.0400      0.065      0.614      0.583      -0.167       0.247
inflation(%)                 0.0030      0.004      0.733      0.517      -0.010       0.016
stock_to_GDP(%)              0.0002      0.000      0.531      0.632      -0.001       0.001
working_population        2.803e-09   5.29e-09      0.530      0.633    -1.4e-08    1.96e-08
Interest_Rate(%)            -0.0011      0.004     -0.308      0.778      -0.012       0.010
==============================================================================
Omnibus:                        2.508   Durbin-Watson:                   2.264
Prob(Omnibus):                  0.285   Jarque-Bera (JB):                2.068
Skew:                          -0.703   Prob(JB):                        0.356
Kurtosis:                       2.290   Cond. No.                     4.61e+12
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 4.61e+12. This might indicate that there are
strong multicollinearity or other numerical problems.

## Visualize with the effective factors (only 2)

In [ ]:
data = annual_gas_summary_more[['avg_all_grades_p($/Gallon)', 'avg_reg_p($/Gallon)','avg_pre_p($/Gallon)']]
sns.pairplot(data, hue = 'avg_all_grades_p($/Gallon)',palette='husl')

# Multilinear regression without the dummy variables

In [34]:
annual_gas_summary_less = annual_gas_summary_more.drop(columns=["avg_reg_p($/Gallon)","avg_midg_p($/Gallon)",
                                                                "avg_pre_p($/Gallon)","avg_dis_p($/Gallon)"])
annual_gas_summary_less

,Year,avg_production(Mmcf),avg_consumption(Mmcf),avg_vol(Mmcf),avg_total_import(Mmcf),avg_toal_export(Mmcf),avg_import_price($/Mmcf),avg_export_price($/Mmcf),avg_all_grades_p($/Gallon),inflation(%),stock_to_GDP(%),working_population,Interest_Rate(%)
0,2001,1.714191e+06,1.853219e+06,6.335558e+06,331411.500000,31106.583333,4.357500,4.383333,1.466167,2.826171,132.1480,181476647,3.410000
1,2002,1.657065e+06,1.918918e+06,6.715545e+06,334622.000000,43019.333333,3.138333,3.339167,1.381833,1.586032,101.0791,183792729,1.173333
2,2003,1.664530e+06,1.856375e+06,6.256805e+06,328645.750000,56660.250000,5.180833,5.582500,1.601083,2.270095,124.5066,186939817,2.104167
3,2004,1.626458e+06,1.866879e+06,6.460054e+06,354879.916667,71178.083333,5.779167,6.069167,1.891250,2.677237,133.6506,188763071,2.395833
4,2005,1.577258e+06,1.834536e+06,6.492884e+06,361752.833333,60716.666667,8.085000,8.010833,2.312167,3.392747,130.4083,191024953,4.250000
5,2006,1.617473e+06,1.808256e+06,6.860307e+06,348856.833333,60329.750000,6.866667,6.831667,2.615083,3.225944,141.6542,193219398,6.020833
6,2007,1.683029e+06,1.925316e+06,6.837505e+06,383965.166667,68537.833333,6.872500,6.905833,2.845500,2.852672,137.8527,195663562,5.791667
7,2008,1.759338e+06,1.939751e+06,6.592182e+06,332008.416667,80271.750000,8.774167,8.774167,3.305083,3.839100,78.7766,196691536,2.166667
8,2009,1.803995e+06,1.909173e+06,7.052343e+06,312613.333333,89363.083333,4.136667,4.354167,2.396667,-0.355546,104.3488,197897475,0.500000
9,2010,1.865156e+06,2.007233e+06,7.052461e+06,311730.000000,94732.416667,4.464167,5.030000,2.833583,1.640043,115.2841,199183839,0.729167
10,2011,2.003029e+06,2.039785e+06,7.004209e+06,289057.750000,125470.833333,4.221667,4.640833,3.576417,3.156842,100.6313,199962562,0.750000
11,2012,2.106940e+06,2.128207e+06,7.501633e+06,261482.416667,134902.333333,2.880833,3.223333,3.686167,2.069337,115.2579,201475828,0.750000
12,2013,2.130186e+06,2.179589e+06,7.149331e+06,240279.666667,131034.416667,3.815000,4.081667,3.576417,1.464833,143.1937,202327635,0.750000
13,2014,2.291480e+06,2.216115e+06,6.620863e+06,224614.916667,126186.833333,5.380833,5.410000,3.442000,1.622223,150.2273,203020518,0.750000
14,2015,2.397670e+06,2.270321e+06,7.171337e+06,226507.750000,148626.083333,3.153333,3.080000,2.513000,0.118627,137.4445,204334050,0.770833
15,2016,2.366671e+06,2.287018e+06,7.577976e+06,250536.500000,194620.666667,2.337500,2.745833,2.252500,1.261583,145.9167,205553963,1.020833
16,2017,2.436486e+06,2.261873e+06,7.304990e+06,252768.916667,262817.000000,2.690000,3.535833,2.530333,2.130110,164.3593,205570247,1.625000
17,2018,2.750739e+06,2.511578e+06,6.654810e+06,240737.000000,300653.500000,2.812500,3.855833,2.817333,2.442583,147.6641,206538862,2.458333
18,2019,3.037243e+06,2.594337e+06,6.901474e+06,228476.333333,388138.083333,2.588333,3.630833,2.685750,1.812210,158.1229,206309620,2.750000
19,2020,3.016870e+06,2.539351e+06,7.456273e+06,212611.666667,440300.666667,2.086667,3.624167,2.259750,1.233584,194.4900,205954426,0.583333

In [37]:
#initialize X, y
X = annual_gas_summary_less.drop(columns = ['avg_all_grades_p($/Gallon)'])
y = annual_gas_summary_less['avg_all_grades_p($/Gallon)']

In [38]:
#Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [39]:
#Scale data
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()
X_train_s = data_scaler.fit_transform(X_train)
X_test_s = data_scaler.fit_transform(X_test)

In [40]:
#create instance of model
model = LinearRegression()

In [41]:
#train the model
model.fit(X_train_s, y_train)

LinearRegression()

In [43]:
#create prediction to test
y_pred = model.predict(X_test_s)

In [44]:
#results
print('Multi-Linear_Regression Model Result:')
print(y_pred.shape)
print('---------------------------------------')
print('intercept: \n', model.intercept_)
print('Coefficients: \n', model.coef_)

Multi-Linear_Regression Model Result:
(5,)
---------------------------------------
intercept:
 2.778238888888772
Coefficients:
 [-11.62512608   0.95862902  -0.66515831  -0.27185754  -0.9046697
   3.19858058   2.475043    -2.25451351   0.40395543   0.72926297
   8.16887592  -0.60303027]

In [45]:
import sklearn.metrics as skm
print('MAE =', round(skm.mean_absolute_error(y_test, y_pred), 2))
print("MSE =", round(skm.mean_squared_error(y_test, y_pred), 2)) 
print("MAE =", round(skm.median_absolute_error(y_test, y_pred), 2)) 
print("EVS =", round(skm.explained_variance_score(y_test, y_pred), 2)) 
print("R2 score =", round(skm.r2_score(y_test, y_pred), 2))

MAE = 0.82
MSE = 0.86
MAE = 0.83
EVS = -0.13
R2 score = -1.79

In [53]:
X = sm.add_constant(X)

C:\Users\kimbe\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

In [54]:
sm_model = sm.OLS(y, X).fit()

In [55]:
predictions = sm_model.predict(X)

In [56]:
print(sm_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       0.887
Model:                            OLS   Adj. R-squared:                  0.693
Method:                 Least Squares   F-statistic:                     4.569
Date:                Sun, 22 May 2022   Prob (F-statistic):             0.0265
Time:                        16:53:43   Log-Likelihood:                 1.2739
No. Observations:                  20   AIC:                             23.45
Df Residuals:                       7   BIC:                             36.40
Df Model:                          12
Covariance Type:            nonrobust
============================================================================================
                               coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------
const                     1479.8497    809.394      1.828      0.110    -434.062    3393.762
Year                        -0.7803      0.424     -1.842      0.108      -1.782       0.222
avg_production(Mmcf)      1.651e-06    3.4e-06      0.485      0.642   -6.39e-06    9.69e-06
avg_consumption(Mmcf)     3.957e-07   3.15e-06      0.126      0.903   -7.04e-06    7.83e-06
avg_vol(Mmcf)             4.362e-07   6.55e-07      0.666      0.527   -1.11e-06    1.98e-06
avg_total_import(Mmcf)   -1.327e-05   1.02e-05     -1.300      0.235   -3.74e-05    1.09e-05
avg_toal_export(Mmcf)     1.637e-06   1.04e-05      0.158      0.879   -2.28e-05    2.61e-05
avg_import_price($/Mmcf)    -0.1539      0.973     -0.158      0.879      -2.454       2.146
avg_export_price($/Mmcf)     0.2370      1.114      0.213      0.838      -2.397       2.871
inflation(%)                 0.3018      0.177      1.705      0.132      -0.117       0.720
stock_to_GDP(%)              0.0009      0.009      0.093      0.929      -0.021       0.023
working_population        4.385e-07   2.07e-07      2.115      0.072   -5.18e-08    9.29e-07
Interest_Rate(%)            -0.0173      0.184     -0.094      0.928      -0.453       0.418
==============================================================================
Omnibus:                        6.353   Durbin-Watson:                   1.880
Prob(Omnibus):                  0.042   Jarque-Bera (JB):                4.208
Skew:                          -1.087   Prob(JB):                        0.122
Kurtosis:                       3.568   Cond. No.                     1.87e+12
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.87e+12. This might indicate that there are
strong multicollinearity or other numerical problems.

# Regression model with original cleaned data - us_gas_data.csv

In [98]:
us_gas_data = pd.read_csv('Resources/cleaned_data/us_gas_data.csv')
us_gas_data

,Year,Month,Gas_Procution(Mmcf),Gas_Consumption(Mmcf),Import_price($/Mcf),Export_price($/Mcf),Total Imports (Mmcf),Total Exports (Mmcf),all_grades($/Gallon),regular($/Gallon),midgrade($/Gallon),premium($/Gallon),diesel($/Gallon),Volumn(Mmcf)
0,2022,2,2856356,3040029.0,5.62,8.22,259389,545563,3.611,3.517,3.939,4.210,4.032,5997164.0
1,2022,1,3180818,3591557.0,6.87,7.04,296179,610102,3.413,3.315,3.766,4.036,3.724,6653327.0
2,2021,12,3266272,2979653.0,4.74,7.40,252626,620886,3.406,3.307,3.771,4.034,3.641,7647859.0
3,2021,11,3161306,2659971.0,5.18,8.10,242405,556982,3.491,3.395,3.836,4.098,3.727,7971480.0
4,2021,10,3219612,2237715.0,4.79,7.97,228203,545055,3.384,3.291,3.723,3.979,3.612,8103211.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,2001,5,1763141,1522382.0,4.95,5.50,321878,28981,1.738,1.702,1.785,1.869,1.496,5749464.0
250,2001,4,1703310,1807170.0,5.35,5.65,318573,23637,1.591,1.552,1.646,1.732,1.422,5252851.0
251,2001,3,1766754,2246633.0,5.42,4.93,358103,32121,1.450,1.409,1.506,1.596,1.399,5041971.0
252,2001,2,1582557,2309464.0,6.45,5.80,328289,26882,1.490,1.450,1.544,1.635,1.492,5240820.0
253,2001,1,1753237,2676998.0,9.47,7.48,373077,25547,1.487,1.447,1.541,1.630,1.524,5609446.0

In [100]:
#initialize X, y
X = us_gas_data.drop(columns = ['all_grades($/Gallon)'])
y = us_gas_data['all_grades($/Gallon)'].values.reshape(-1,1)

In [101]:
#Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [102]:
#Scale data
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()
X_train_s = data_scaler.fit_transform(X_train)
X_test_s = data_scaler.fit_transform(X_test)

In [103]:
#create instance of model
model = LinearRegression()

In [104]:
#train the model
model.fit(X_train_s, y_train)

LinearRegression()

In [105]:
#create prediction to test
y_pred = model.predict(X_train_s)

In [106]:
#results
print('Multi-Linear_Regression Model Result:')
print(y_pred.shape)
print('---------------------------------------')
print('intercept: \n', model.intercept_)
print('Coefficients: \n', model.coef_)

Multi-Linear_Regression Model Result:
(190, 1)
---------------------------------------
intercept:
 [2.64834737]
Coefficients:
 [[ 8.20380693e-03  1.58964056e-03 -6.65370864e-04 -6.87580030e-04
   5.83311572e-03 -4.69345287e-03 -9.77198795e-04  5.93297343e-04
   8.40873255e-01 -5.70915364e-01  4.53692822e-01 -7.27674098e-03
  -1.00277176e-03]]

In [107]:
X = sm.add_constant(X)

C:\Users\kimbe\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

In [108]:
sm_model = sm.OLS(y, X).fit()

In [109]:
predictions = sm_model.predict(X)

In [110]:
print(sm_model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                      y   R-squared:                       1.000
Model:                            OLS   Adj. R-squared:                  1.000
Method:                 Least Squares   F-statistic:                 2.892e+05
Date:                Sun, 22 May 2022   Prob (F-statistic):               0.00
Time:                        21:10:24   Log-Likelihood:                 950.71
No. Observations:                 254   AIC:                            -1873.
Df Residuals:                     240   BIC:                            -1824.
Df Model:                          13
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                    -3.1637      0.733     -4.315      0.000      -4.608      -1.719
Year                      0.0016      0.000      4.324      0.000       0.001       0.002
Month                     0.0003      0.000      1.591      0.113   -7.77e-05       0.001
Gas_Procution(Mmcf)   -4.113e-09   4.29e-09     -0.958      0.339   -1.26e-08    4.35e-09
Gas_Consumption(Mmcf)  1.067e-09    1.5e-09      0.710      0.478   -1.89e-09    4.03e-09
Import_price($/Mcf)       0.0024      0.001      3.390      0.001       0.001       0.004
Export_price($/Mcf)      -0.0018      0.001     -2.479      0.014      -0.003      -0.000
Total Imports (Mmcf)  -3.201e-08   1.54e-08     -2.076      0.039   -6.24e-08   -1.63e-09
Total Exports (Mmcf)  -8.102e-09   1.13e-08     -0.715      0.475   -3.04e-08    1.42e-08
regular($/Gallon)         1.1536      0.022     52.062      0.000       1.110       1.197
midgrade($/Gallon)       -0.6963      0.049    -14.176      0.000      -0.793      -0.600
premium($/Gallon)         0.5469      0.035     15.517      0.000       0.477       0.616
diesel($/Gallon)         -0.0094      0.003     -3.412      0.001      -0.015      -0.004
Volumn(Mmcf)            4.06e-10   9.08e-10      0.447      0.655   -1.38e-09    2.19e-09
==============================================================================
Omnibus:                       23.839   Durbin-Watson:                   0.626
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               58.402
Skew:                          -0.408   Prob(JB):                     2.08e-13
Kurtosis:                       5.203   Cond. No.                     1.50e+10
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.5e+10. This might indicate that there are
strong multicollinearity or other numerical problems.

# Regression with original data but without the dummies

In [46]:
us_gas_data_no_dummies = us_gas_data.drop(columns=["regular($/Gallon)","midgrade($/Gallon)","premium($/Gallon)",
                                                  "diesel($/Gallon)"])
us_gas_data_no_dummies

,Year,Month,Gas_Production(Mmcf),Gas_Consumption(Mmcf),Import_price($/Mcf),Export_price($/Mcf),Total Imports (Mmcf),Total Exports (Mmcf),all_grades($/Gallon),Volumn(Mmcf)
0,2022,2,2856356.0,3040029.0,5.62,8.22,259389.0,545563.0,3.611,5997164.0
1,2022,1,3180818.0,3591557.0,6.87,7.04,296179.0,610102.0,3.413,6653327.0
2,2021,12,3266272.0,2979653.0,4.74,7.40,252626.0,620886.0,3.406,7647859.0
3,2021,11,3161306.0,2659971.0,5.18,8.10,242405.0,556982.0,3.491,7971480.0
4,2021,10,3219612.0,2237715.0,4.79,7.97,228203.0,545055.0,3.384,8103211.0
...,...,...,...,...,...,...,...,...,...,...
249,2001,5,1763141.0,1522382.0,4.95,5.50,321878.0,28981.0,1.738,5749464.0
250,2001,4,1703310.0,1807170.0,5.35,5.65,318573.0,23637.0,1.591,5252851.0
251,2001,3,1766754.0,2246633.0,5.42,4.93,358103.0,32121.0,1.450,5041971.0
252,2001,2,1582557.0,2309464.0,6.45,5.80,328289.0,26882.0,1.490,5240820.0
253,2001,1,1753237.0,2676998.0,9.47,7.48,373077.0,25547.0,1.487,5609446.0

In [49]:
#initialize X, y
X = us_gas_data_no_dummies.drop(columns = ['all_grades($/Gallon)'])
y = us_gas_data_no_dummies['all_grades($/Gallon)']

In [50]:
#Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [51]:
#Scale data
from sklearn.preprocessing import StandardScaler
data_scaler = StandardScaler()
X_train_s = data_scaler.fit_transform(X_train)
X_test_s = data_scaler.fit_transform(X_test)

In [52]:
#create instance of model
model = LinearRegression()

In [53]:
#train the model
model.fit(X_train_s, y_train)

LinearRegression()

In [54]:
#create prediction to test
y_pred = model.predict(X_test_s)

In [55]:
#results
print('Multi-Linear_Regression Model Result:')
print(y_pred.shape)
print('---------------------------------------')
print('intercept: \n', model.intercept_)
print('Coefficients: \n', model.coef_)

Multi-Linear_Regression Model Result:
(64,)
---------------------------------------
intercept:
 2.6507999999999834
Coefficients:
 [ 0.97432131  0.03026545 -0.32562536 -0.1117177   0.25085793  0.08023885
 -0.12294204 -0.27945977  0.0487995 ]

In [56]:
X = sm.add_constant(X)

C:\Users\Phoeb\anaconda3\lib\site-packages\statsmodels\tsa\tsatools.py:142: FutureWarning: In a future version of pandas all arguments of concat except for the argument 'objs' will be keyword-only
  x = pd.concat(x[::order], 1)

In [57]:
sm_model = sm.OLS(y, X).fit()

In [58]:
predictions = sm_model.predict(X)

In [59]:
print(sm_model.summary())

                             OLS Regression Results
================================================================================
Dep. Variable:     all_grades($/Gallon)   R-squared:                       0.539
Model:                              OLS   Adj. R-squared:                  0.522
Method:                   Least Squares   F-statistic:                     31.68
Date:                  Wed, 25 May 2022   Prob (F-statistic):           2.09e-36
Time:                          20:25:09   Log-Likelihood:                -177.70
No. Observations:                   254   AIC:                             375.4
Df Residuals:                       244   BIC:                             410.8
Df Model:                             9
Covariance Type:              nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                  -314.5936     35.100     -8.963      0.000    -383.731    -245.456
Year                      0.1584      0.018      8.977      0.000       0.124       0.193
Month                    -0.0036      0.017     -0.216      0.830      -0.037       0.030
Gas_Production(Mmcf)  -4.231e-07   2.96e-07     -1.429      0.154   -1.01e-06     1.6e-07
Gas_Consumption(Mmcf) -3.186e-07   1.03e-07     -3.090      0.002   -5.22e-07   -1.16e-07
Import_price($/Mcf)       0.0998      0.059      1.695      0.091      -0.016       0.216
Export_price($/Mcf)       0.0596      0.061      0.972      0.332      -0.061       0.180
Total Imports (Mmcf)  -1.422e-06   1.25e-06     -1.136      0.257   -3.89e-06    1.04e-06
Total Exports (Mmcf)  -2.362e-06   7.96e-07     -2.969      0.003   -3.93e-06   -7.95e-07
Volumn(Mmcf)           6.082e-08   7.64e-08      0.796      0.427   -8.96e-08    2.11e-07
==============================================================================
Omnibus:                        4.646   Durbin-Watson:                   0.236
Prob(Omnibus):                  0.098   Jarque-Bera (JB):                4.736
Skew:                           0.327   Prob(JB):                       0.0937
Kurtosis:                       2.857   Cond. No.                     8.54e+09
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 8.54e+09. This might indicate that there are
strong multicollinearity or other numerical problems.