In [ ]:
import pandas as pd
from sklearn.linear_model import  LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import tensorflow as tf

In [3]:
us_gas_data = pd.read_csv('us_gas_data.csv')
us_gas_data

,Year,Month,Gas_Production(Mmcf),Gas_Consumption(Mmcf),Import_price($/Mcf),Export_price($/Mcf),Total Imports (Mmcf),Total Exports (Mmcf),all_grades($/Gallon),regular($/Gallon),midgrade($/Gallon),premium($/Gallon),diesel($/Gallon),Volumn(Mmcf)
0,2022,2,2856356,3040029.0,5.62,8.22,259389,545563,3.611,3.517,3.939,4.210,4.032,5997164.0
1,2022,1,3180818,3591557.0,6.87,7.04,296179,610102,3.413,3.315,3.766,4.036,3.724,6653327.0
2,2021,12,3266272,2979653.0,4.74,7.40,252626,620886,3.406,3.307,3.771,4.034,3.641,7647859.0
3,2021,11,3161306,2659971.0,5.18,8.10,242405,556982,3.491,3.395,3.836,4.098,3.727,7971480.0
4,2021,10,3219612,2237715.0,4.79,7.97,228203,545055,3.384,3.291,3.723,3.979,3.612,8103211.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,2001,5,1763141,1522382.0,4.95,5.50,321878,28981,1.738,1.702,1.785,1.869,1.496,5749464.0
250,2001,4,1703310,1807170.0,5.35,5.65,318573,23637,1.591,1.552,1.646,1.732,1.422,5252851.0
251,2001,3,1766754,2246633.0,5.42,4.93,358103,32121,1.450,1.409,1.506,1.596,1.399,5041971.0
252,2001,2,1582557,2309464.0,6.45,5.80,328289,26882,1.490,1.450,1.544,1.635,1.492,5240820.0
253,2001,1,1753237,2676998.0,9.47,7.48,373077,25547,1.487,1.447,1.541,1.630,1.524,5609446.0

In [4]:
us_gas_data.columns

Index(['Year', 'Month', 'Gas_Production(Mmcf)', 'Gas_Consumption(Mmcf)',
       'Import_price($/Mcf)', 'Export_price($/Mcf)', 'Total Imports (Mmcf)',
       'Total Exports (Mmcf)', 'all_grades($/Gallon)', 'regular($/Gallon)',
       'midgrade($/Gallon)', 'premium($/Gallon)', 'diesel($/Gallon)',
       'Volumn(Mmcf)'],
      dtype='object')

In [5]:
us_gas_data.dtypes

Year                       int64
Month                      int64
Gas_Production(Mmcf)       int64
Gas_Consumption(Mmcf)    float64
Import_price($/Mcf)      float64
Export_price($/Mcf)      float64
Total Imports (Mmcf)       int64
Total Exports (Mmcf)       int64
all_grades($/Gallon)     float64
regular($/Gallon)        float64
midgrade($/Gallon)       float64
premium($/Gallon)        float64
diesel($/Gallon)         float64
Volumn(Mmcf)             float64
dtype: object

In [6]:
us_gas_data = us_gas_data.astype({'Gas_Production(Mmcf)':float,
              'Total Imports (Mmcf)' : float,
              'Total Exports (Mmcf)': float })
us_gas_data.dtypes

Year                       int64
Month                      int64
Gas_Production(Mmcf)     float64
Gas_Consumption(Mmcf)    float64
Import_price($/Mcf)      float64
Export_price($/Mcf)      float64
Total Imports (Mmcf)     float64
Total Exports (Mmcf)     float64
all_grades($/Gallon)     float64
regular($/Gallon)        float64
midgrade($/Gallon)       float64
premium($/Gallon)        float64
diesel($/Gallon)         float64
Volumn(Mmcf)             float64
dtype: object

In [7]:
us_gas_data.describe()

,Year,Month,Gas_Production(Mmcf),Gas_Consumption(Mmcf),Import_price($/Mcf),Export_price($/Mcf),Total Imports (Mmcf),Total Exports (Mmcf),all_grades($/Gallon),regular($/Gallon),midgrade($/Gallon),premium($/Gallon),diesel($/Gallon),Volumn(Mmcf)
count,254.000000,254.000000,2.540000e+02,2.540000e+02,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,254.000000,2.540000e+02
mean,2011.086614,6.460630,2.130387e+06,2.127122e+06,4.459764,4.955591,288559.976378,168158.531496,2.629945,2.562823,2.753433,2.909291,2.798303,6.906497e+06
std,6.121334,3.473847,5.071507e+05,4.740569e+05,2.161772,1.964109,58264.662838,146897.706073,0.718712,0.713631,0.736901,0.761305,0.844100,8.031707e+05
min,2001.000000,1.000000,1.400941e+06,1.368369e+06,1.510000,2.040000,174225.000000,23637.000000,1.127000,1.086000,1.179000,1.271000,1.152000,5.041971e+06
25%,2006.000000,3.000000,1.694616e+06,1.743070e+06,2.732500,3.510000,238368.750000,64439.500000,2.198500,2.109250,2.287750,2.430750,2.311250,6.288639e+06
50%,2011.000000,6.000000,1.994746e+06,2.068744e+06,4.035000,4.450000,282064.500000,118918.500000,2.640500,2.555000,2.786000,2.950500,2.839500,7.002317e+06
75%,2016.000000,9.000000,2.428004e+06,2.428177e+06,5.627500,6.015000,333876.250000,224495.750000,3.124000,3.062000,3.247750,3.470250,3.374000,7.545798e+06
max,2022.000000,12.000000,3.266272e+06,3.591557e+06,11.990000,12.680000,426534.000000,620886.000000,4.114000,4.062000,4.181000,4.298000,4.703000,8.384087e+06

In [8]:
# Neural network

## Monthly data analysis

In [9]:
#group by data 'month' - gas production
monthly_gas_production = us_gas_data.groupby(['Month']).mean()['Gas_Production(Mmcf)']
monthly_gas_consumption = us_gas_data.groupby(['Month']).mean()['Gas_Consumption(Mmcf)']
monthly_gas_import_p = us_gas_data.groupby(['Month']).mean()['Import_price($/Mcf)']
monthly_gas_export_p = us_gas_data.groupby(['Month']).mean()['Export_price($/Mcf)']
monthly_total_import = us_gas_data.groupby(['Month']).mean()['Total Imports (Mmcf)']
monthly_total_export = us_gas_data.groupby(['Month']).mean()['Total Exports (Mmcf)']
monthly_avg_all_grades_p = us_gas_data.groupby(['Month']).mean()['all_grades($/Gallon)']
monthly_avg_reg_p = us_gas_data.groupby(['Month']).mean()['regular($/Gallon)']
monthly_avg_midg_p = us_gas_data.groupby(['Month']).mean()['midgrade($/Gallon)']
monthly_avg_pre_p = us_gas_data.groupby(['Month']).mean()['premium($/Gallon)']
monthly_avg_dis_p = us_gas_data.groupby(['Month']).mean()['diesel($/Gallon)']
monthly_avg_vol = us_gas_data.groupby(['Month']).mean()['Volumn(Mmcf)']

In [10]:
# create annual summary, reorder columns
monthly_gas_df = pd.DataFrame({
    'avg_production(Mmcf)': monthly_gas_production,
    'avg_consumption(Mmcf)': monthly_gas_consumption,
    'avg_vol(Mmcf)': monthly_avg_vol,
    'avg_total_import(Mmcf)': monthly_total_import,
    'avg_toal_export(Mmcf)': monthly_total_export,
    'avg_import_price($/Mmcf)': monthly_gas_import_p,
    'avg_export_price($/Mmcf)': monthly_gas_export_p,
    'avg_all_grades_p($/Gallon)': monthly_avg_all_grades_p,
    'avg_reg_p($/Gallon)': monthly_avg_reg_p,
    'avg_midg_p($/Gallon)': monthly_avg_midg_p,
    'avg_pre_p($/Gallon)': monthly_avg_pre_p,
    'avg_dis_p($/Gallon)': monthly_avg_dis_p 
})

monthly_gas_df.head()

,avg_production(Mmcf),avg_consumption(Mmcf),avg_vol(Mmcf),avg_total_import(Mmcf),avg_toal_export(Mmcf),avg_import_price($/Mmcf),avg_export_price($/Mmcf),avg_all_grades_p($/Gallon),avg_reg_p($/Gallon),avg_midg_p($/Gallon),avg_pre_p($/Gallon),avg_dis_p($/Gallon)
Month,,,,,,,,,,,,
1,2.176798e+06,2.900654e+06,6.573022e+06,329209.863636,191141.227273,5.346818,5.325909,2.434045,2.365364,2.559727,2.721318,2.693909
2,1.980882e+06,2.584856e+06,6.020566e+06,290862.454545,172537.863636,5.126364,5.646364,2.492545,2.424727,2.616136,2.775182,2.732500
3,2.156907e+06,2.372026e+06,5.850328e+06,301041.476190,177765.095238,4.628571,4.960000,2.574619,2.509286,2.688333,2.837000,2.756238
4,2.087371e+06,1.924890e+06,6.059108e+06,273109.666667,152638.666667,4.178095,4.724762,2.671238,2.605000,2.787810,2.937000,2.790619
5,2.147666e+06,1.747473e+06,6.468206e+06,272039.666667,157155.333333,4.174762,4.860476,2.758190,2.694000,2.876667,3.026857,2.820333

In [42]:
from

avg_production(Mmcf)          float64
avg_consumption(Mmcf)         float64
avg_vol(Mmcf)                 float64
avg_total_import(Mmcf)        float64
avg_toal_export(Mmcf)         float64
avg_import_price($/Mmcf)      float64
avg_export_price($/Mmcf)      float64
avg_all_grades_p($/Gallon)    float64
avg_reg_p($/Gallon)           float64
avg_midg_p($/Gallon)          float64
avg_pre_p($/Gallon)           float64
avg_dis_p($/Gallon)           float64
dtype: object