In [1]:
import pandas as pd

In [2]:
us_gas_data = pd.read_csv('../Resources/cleaned_data/us_gas_data.csv')
us_gas_data

,Year,Month,Gas_Procution(Mmcf),Gas_Consumption(Mmcf),Import_price($/Mcf),Export_price($/Mcf),Total Imports (Mmcf),Total Exports (Mmcf),all_grades($/Gallon),regular($/Gallon),midgrade($/Gallon),premium($/Gallon),diesel($/Gallon),Volumn(Mmcf)
0,2022,2,2856356,3040029.0,5.62,8.22,259389,545563,3.611,3.517,3.939,4.210,4.032,5997164.0
1,2022,1,3180818,3591557.0,6.87,7.04,296179,610102,3.413,3.315,3.766,4.036,3.724,6653327.0
2,2021,12,3266272,2979653.0,4.74,7.40,252626,620886,3.406,3.307,3.771,4.034,3.641,7647859.0
3,2021,11,3161306,2659971.0,5.18,8.10,242405,556982,3.491,3.395,3.836,4.098,3.727,7971480.0
4,2021,10,3219612,2237715.0,4.79,7.97,228203,545055,3.384,3.291,3.723,3.979,3.612,8103211.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
249,2001,5,1763141,1522382.0,4.95,5.50,321878,28981,1.738,1.702,1.785,1.869,1.496,5749464.0
250,2001,4,1703310,1807170.0,5.35,5.65,318573,23637,1.591,1.552,1.646,1.732,1.422,5252851.0
251,2001,3,1766754,2246633.0,5.42,4.93,358103,32121,1.450,1.409,1.506,1.596,1.399,5041971.0
252,2001,2,1582557,2309464.0,6.45,5.80,328289,26882,1.490,1.450,1.544,1.635,1.492,5240820.0
253,2001,1,1753237,2676998.0,9.47,7.48,373077,25547,1.487,1.447,1.541,1.630,1.524,5609446.0

In [3]:
us_gas_data.columns

Index(['Year', 'Month', 'Gas_Procution(Mmcf)', 'Gas_Consumption(Mmcf)',
       'Import_price($/Mcf)', 'Export_price($/Mcf)', 'Total Imports (Mmcf)',
       'Total Exports (Mmcf)', 'all_grades($/Gallon)', 'regular($/Gallon)',
       'midgrade($/Gallon)', 'premium($/Gallon)', 'diesel($/Gallon)',
       'Volumn(Mmcf)'],
      dtype='object')

In [4]:
us_gas_data.dtypes

Year                       int64
Month                      int64
Gas_Procution(Mmcf)        int64
Gas_Consumption(Mmcf)    float64
Import_price($/Mcf)      float64
Export_price($/Mcf)      float64
Total Imports (Mmcf)       int64
Total Exports (Mmcf)       int64
all_grades($/Gallon)     float64
regular($/Gallon)        float64
midgrade($/Gallon)       float64
premium($/Gallon)        float64
diesel($/Gallon)         float64
Volumn(Mmcf)             float64
dtype: object

In [5]:
us_gas_data = us_gas_data.astype({'Gas_Procution(Mmcf)':float,
              'Total Imports (Mmcf)' : float,
              'Total Exports (Mmcf)': float })
us_gas_data.dtypes

Year                       int64
Month                      int64
Gas_Procution(Mmcf)      float64
Gas_Consumption(Mmcf)    float64
Import_price($/Mcf)      float64
Export_price($/Mcf)      float64
Total Imports (Mmcf)     float64
Total Exports (Mmcf)     float64
all_grades($/Gallon)     float64
regular($/Gallon)        float64
midgrade($/Gallon)       float64
premium($/Gallon)        float64
diesel($/Gallon)         float64
Volumn(Mmcf)             float64
dtype: object

In [6]:
#group by data 'month' - gas production
monthly_gas_production = us_gas_data.groupby(['Month']).mean()['Gas_Procution(Mmcf)']
monthly_gas_consumption = us_gas_data.groupby(['Month']).mean()['Gas_Consumption(Mmcf)']
monthly_gas_import_p = us_gas_data.groupby(['Month']).mean()['Import_price($/Mcf)']
monthly_gas_export_p = us_gas_data.groupby(['Month']).mean()['Export_price($/Mcf)']
monthly_total_import = us_gas_data.groupby(['Month']).mean()['Total Imports (Mmcf)']
monthly_total_export = us_gas_data.groupby(['Month']).mean()['Total Exports (Mmcf)']
monthly_avg_all_grades_p = us_gas_data.groupby(['Month']).mean()['all_grades($/Gallon)']
monthly_avg_reg_p = us_gas_data.groupby(['Month']).mean()['regular($/Gallon)']
monthly_avg_midg_p = us_gas_data.groupby(['Month']).mean()['midgrade($/Gallon)']
monthly_avg_pre_p = us_gas_data.groupby(['Month']).mean()['premium($/Gallon)']
monthly_avg_dis_p = us_gas_data.groupby(['Month']).mean()['diesel($/Gallon)']
monthly_avg_vol = us_gas_data.groupby(['Month']).mean()['Volumn(Mmcf)']

In [7]:
# create annual summary, reorder columns
monthly_gas_summary = pd.DataFrame({
    'avg_production(Mmcf)': monthly_gas_production,
    'avg_consumption(Mmcf)': monthly_gas_consumption,
    'avg_vol(Mmcf)': monthly_avg_vol,
    'avg_total_import(Mmcf)': monthly_total_import,
    'avg_toal_export(Mmcf)': monthly_total_export,
    'avg_import_price($/Mmcf)': monthly_gas_import_p,
    'avg_export_price($/Mmcf)': monthly_gas_export_p,
    'avg_all_grades_p($/Gallon)': monthly_avg_all_grades_p,
    'avg_reg_p($/Gallon)': monthly_avg_reg_p,
    'avg_midg_p($/Gallon)': monthly_avg_midg_p,
    'avg_pre_p($/Gallon)': monthly_avg_pre_p,
    'avg_dis_p($/Gallon)': monthly_avg_dis_p 
})

monthly_gas_summary.head()

,avg_production(Mmcf),avg_consumption(Mmcf),avg_vol(Mmcf),avg_total_import(Mmcf),avg_toal_export(Mmcf),avg_import_price($/Mmcf),avg_export_price($/Mmcf),avg_all_grades_p($/Gallon),avg_reg_p($/Gallon),avg_midg_p($/Gallon),avg_pre_p($/Gallon),avg_dis_p($/Gallon)
Month,,,,,,,,,,,,
1,2.176798e+06,2.900654e+06,6.573022e+06,329209.863636,191141.227273,5.346818,5.325909,2.434045,2.365364,2.559727,2.721318,2.693909
2,1.980882e+06,2.584856e+06,6.020566e+06,290862.454545,172537.863636,5.126364,5.646364,2.492545,2.424727,2.616136,2.775182,2.732500
3,2.156907e+06,2.372026e+06,5.850328e+06,301041.476190,177765.095238,4.628571,4.960000,2.574619,2.509286,2.688333,2.837000,2.756238
4,2.087371e+06,1.924890e+06,6.059108e+06,273109.666667,152638.666667,4.178095,4.724762,2.671238,2.605000,2.787810,2.937000,2.790619
5,2.147666e+06,1.747473e+06,6.468206e+06,272039.666667,157155.333333,4.174762,4.860476,2.758190,2.694000,2.876667,3.026857,2.820333

In [8]:
monthly_gas_summary.dtypes

avg_production(Mmcf)          float64
avg_consumption(Mmcf)         float64
avg_vol(Mmcf)                 float64
avg_total_import(Mmcf)        float64
avg_toal_export(Mmcf)         float64
avg_import_price($/Mmcf)      float64
avg_export_price($/Mmcf)      float64
avg_all_grades_p($/Gallon)    float64
avg_reg_p($/Gallon)           float64
avg_midg_p($/Gallon)          float64
avg_pre_p($/Gallon)           float64
avg_dis_p($/Gallon)           float64
dtype: object

In [9]:
monthly_gas_summary.reset_index()

,Month,avg_production(Mmcf),avg_consumption(Mmcf),avg_vol(Mmcf),avg_total_import(Mmcf),avg_toal_export(Mmcf),avg_import_price($/Mmcf),avg_export_price($/Mmcf),avg_all_grades_p($/Gallon),avg_reg_p($/Gallon),avg_midg_p($/Gallon),avg_pre_p($/Gallon),avg_dis_p($/Gallon)
0,1,2.176798e+06,2.900654e+06,6.573022e+06,329209.863636,191141.227273,5.346818,5.325909,2.434045,2.365364,2.559727,2.721318,2.693909
1,2,1.980882e+06,2.584856e+06,6.020566e+06,290862.454545,172537.863636,5.126364,5.646364,2.492545,2.424727,2.616136,2.775182,2.732500
2,3,2.156907e+06,2.372026e+06,5.850328e+06,301041.476190,177765.095238,4.628571,4.960000,2.574619,2.509286,2.688333,2.837000,2.756238
3,4,2.087371e+06,1.924890e+06,6.059108e+06,273109.666667,152638.666667,4.178095,4.724762,2.671238,2.605000,2.787810,2.937000,2.790619
4,5,2.147666e+06,1.747473e+06,6.468206e+06,272039.666667,157155.333333,4.174762,4.860476,2.758190,2.694000,2.876667,3.026857,2.820333
5,6,2.082796e+06,1.745842e+06,6.819003e+06,269727.523810,150197.000000,4.220000,4.810952,2.768000,2.703762,2.887905,3.039286,2.825905
6,7,2.166042e+06,1.934052e+06,7.073847e+06,296586.047619,156453.000000,4.180952,4.798095,2.747810,2.682286,2.869190,3.023048,2.823476
7,8,2.173139e+06,1.949600e+06,7.317573e+06,292025.714286,157834.714286,3.976667,4.635714,2.736476,2.670333,2.859048,3.014571,2.832190
8,9,2.084450e+06,1.740402e+06,7.655601e+06,271802.571429,158814.095238,3.919048,4.585714,2.738857,2.671762,2.863810,3.020571,2.852905
9,10,2.176682e+06,1.837722e+06,7.915973e+06,276281.714286,165011.571429,4.166190,4.724762,2.649095,2.580048,2.779286,2.937619,2.859905
10,11,2.132955e+06,2.107965e+06,7.837963e+06,273494.000000,181307.095238,4.618571,5.067143,2.543810,2.473667,2.676238,2.837571,2.829571
11,12,2.203868e+06,2.621350e+06,7.344842e+06,314493.666667,195743.761905,4.907143,5.276667,2.460524,2.389619,2.592810,2.756810,2.770190

In [11]:
monthly_gas_summary.to_csv('../Resources/cleaned_data/Monthly_us_gas_data.csv', index=False)

# Send it to our Database

In [12]:
from sqlalchemy import create_engine
from getpass import getpass

In [14]:
#store password variable
password = getpass("password")

passwordÂ·Â·Â·Â·Â·Â·Â·Â·

In [15]:
# connect to database
engine = create_engine(f"postgresql://postgres:{password}@localhost:5432/gas_data")

In [16]:
# import my data to database
monthly_gas_summary.to_sql(name="gas_data", con=engine, index = False, if_exists='append')